#cmakedefine CONFIG_ICONV @CONFIG_ICONV@
#cmakedefine CONFIG_LARGE_TILES @CONFIG_LARGE_TILES@
#cmakedefine CONFIG_DIRECTWRITE @CONFIG_DIRECTWRITE@
#cmakedefine CONFIG_FONTCONFIG @CONFIG_FONTCONFIG@
#define CONFIG_SOURCEVERSION "@CONFIG_SOURCEVERSION@"
#cmakedefine HAVE_STRDUP @HAVE_STRDUP@
#cmakedefine HAVE_STRNDUP @HAVE_STRNDUP@
#cmakedefine CONFIG_ASM @CONFIG_ASM@
